# Trigger presubmit tests for trusted contributors
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/trusted-contribution
# Install: https://github.com/apps/trusted-contributions-gcf

trustedContributors:
  - "dependabot[bot]"
  - "renovate-bot"
  - "renovate[bot]"
  - "forking-renovate[bot]"
  - "release-please[bot]"
annotations:
  # Trigger Cloud Build tests
  - type: comment
    text: "/gcbrun"
  # Trigger Kokoro example
  # - type: label
  #   text: "kokoro:force-run"
